language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
install:
  - pip install -q coverage flake8
before_script:
  - psql -c 'CREATE DATABASE smart_manager;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
